# Generated by Django 3.2.16 on 2026-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20260116_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article',
            field=models.CharField(default='Одинокий пост', max_length=30),
            preserve_default=False,
        ),
    ]
