# Generated by Django 3.2.16 on 2026-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='Какое-то общество', unique=True),
            preserve_default=False,
        ),
    ]
