# Generated by Django 3.2.16 on 2026-01-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article',
        ),
    ]
